name: Jira ticket transition
description: Transistions a ticket in JIRA

inputs:
  issue:
    description: The key of the issue to be moved
    required: true
  comment:
    description: A comment to add when transitioning ticket
    required: true
  STATUS:
    description: The status to transition ticket to
    required: true
  JIRA_BASE_URL: 
    description: The base url to query jira
    required: true
  JIRA_USER_EMAIL:
    required: true
    description: The email to log in to jira with
  JIRA_API_TOKEN:     
    required: true
    description: The api token to authenticate with jira

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Transition JIRA ticket
      id: transition-JIRA-ticket
      shell: bash
      env:
        ISSUE_KEY: ${{ inputs.issue }}
        COMMENT: ${{ inputs.comment }}
        STATUS: ${{ inputs.STATUS }}
        JIRA_BASE_URL: ${{ inputs.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ inputs.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ inputs.JIRA_API_TOKEN }}
      run: |
        pip install jira
        python ${{ github.action_path }}/jira_ticket_transition.py