name: Jira Add Comment
author: Stefan Popescu
description: Add a comment to an issue
branding:
  icon: align-left
  color: blue

inputs:
  issue:
    description: Key of the issue to be commented on
    required: true
  comment:
    description: Comment
    required: true

runs:
  using: composite
  steps:
    - name: Login to Jira
      uses: atlassian/gajira-login@v3

    - name: Comment on issue
      continue-on-error: true
      uses: atlassian/gajira-comment@v3
      with:
        issue: ${{ inputs.issue }}
        comment: ${{ inputs.comment }}
