name: Terraform static checks

on:
  workflow_call:
    inputs:
      soft_fail:
        description: 'Do not return an error code if there are failed checks'
        required: false
        type: boolean
        default: true

jobs:
  checkov-job:
    runs-on: self-hosted
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          quiet: true # optional: display only failed checks
          soft_fail: ${{ inputs.soft_fail }} # optional: do not return an error code if there are failed checks
          framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
          output_format: cli # optional: the output format, one of: cli, json, junitxml, github_failed_only
          download_external_modules: false # optional: download external terraform modules from public git repositories and terraform registry
#          log_level: DEBUG # optional: set log level. Default WARNING
#          check: CKV_AWS_1 # optional: run only a specific check_id. can be comma separated list
