name: Delete on-prem environment

on:
  workflow_call:
    inputs:
      hostname-prefix:
        description: 'The hostname prefix of the environment to delete'
        required: true
        type: string
      container-type:
        description: 'The type of the environment to delete'
        required: true
        type: string
      project:
        description: 'The project of the environment to delete'
        required: true
        type: string
      job-timeout:
        description: 'Jenkins job timeout period. Default 600 seconds'
        required: false
        type: number
        default: 600
      jenkins-url:
        description: 'The URL for Jenkins'
        required: true
        type: string
      runs-on:
        description: 'The tags to pass to the runs-on configuration'
        required: true
        type: string
    secrets:
      JENKINS_USER:
        required: true
      JENKINS_TOKEN:
        required: true
      

jobs:
  delete-onprem-env:
    runs-on: ${{ fromJson(inputs.runs-on) }}
    steps:
      - name: Invoke Jenkins
        uses: estherk0/jenkins-trigger@28c29b61f13bdc3d46b4a6dc9b2a8248ed3c6f0e
        with:
          url: ${{ inputs.jenkins-url }}
          user_name: ${{ secrets.JENKINS_USER }}
          api_token: ${{ secrets.JENKINS_TOKEN }}
          job_name: lxd-hammer-delete
          parameter: |
            {
              "hostname_prefix": "${{ inputs.hostname-prefix }}",
              "container_type": "${{ inputs.container-type }}",
              "project": "${{ inputs.project }}"
            }
          timeout: ${{ inputs.job-timeout }}
          wait: true
