name: Jira validation reusable workflow

on:
  workflow_call:
    inputs:
      runs-on:
        description: The type of machine to run the job on. The machine can be either a GitHub-hosted runner, or a self-hosted runner.
        required: false
        type: string
        default: ubuntu-latest
      CONTEXT_ENV:
        description: Dev or Test env
        required: true
        type: string
    secrets:
      JIRA_BASE_URL:
        required: true
      JIRA_USER_EMAIL:
        required: true
      JIRA_API_TOKEN:
        required: true

jobs:
  validate-ticket:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: EmesaDEV/actions/jira-validate@v0.22.0
        with:
          CONTEXT_ENV: ${{ inputs.CONTEXT_ENV }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
