name: Jira validation reusable workflow

on:
  workflow_call:
    inputs:
      runs-on:
        description: The type of machine to run the job on. The machine can be either a GitHub-hosted runner, or a self-hosted runner.
        required: false
        type: string
        default: ubuntu-latest
      CONTEXT_ENV:
        description: Prod env
        required: true
        type: string
    secrets:
      JIRA_BASE_URL:
        required: true
      JIRA_USER_EMAIL:
        required: true
      JIRA_API_TOKEN:
        required: true

jobs:
 validate-ticket:
    name: Validate Jira ticket
    if: ${{ github.event.pull_request.merged }}
    runs-on: ${{ inputs.runs-on }}
    outputs:
      current_branch: ${{ steps.branch-names.outputs.current_branch }}
      run_url: ${{ steps.validate-ticket.outputs.run_url }}
    steps:
      - name: Get branch names
        id: branch-names
        uses: tj-actions/branch-names@v8.0.1
      - name: Validate ticket
        id: validate-ticket
        uses: EmesaDEV/actions/jira-validate@HMR-31567
        with:
          CONTEXT_ENV: ${{ inputs.CONTEXT_ENV }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Transition to Merged
        uses: EmesaDEV/actions/jira-transition@HMR-31567
        with:
          issue: ${{ steps.branch-names.outputs.current_branch }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          comment: Ticket merged with master via ${{ steps.validate-ticket.outputs.run_url }}
          STATUS: Merged