name: Terraform static checks

on:
  workflow_call:
    inputs:
      runs-on:
        description: The type of machine to run the job on. The machine can be either a GitHub-hosted runner, or a self-hosted runner.
        required: false
        type: string
        default: self-hosted
      continue-on-error:
        description: Do not return an error code if there are failed checks
        required: false
        type: boolean
        default: true
      log-level:
        description: Log level
        required: false
        type: string
        default: WARNING

jobs:
  checkov-job:
    runs-on: ${{ inputs.runs-on }}
    name: checkov-action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12.1857.0
        with:
          directory: .
          quiet: true # optional: display only failed checks
          soft_fail: ${{ inputs.continue-on-error }}
          framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
          output_format: cli # optional: the output format, one of: cli, json, junitxml, github_failed_only
          download_external_modules: false # optional: download external terraform modules from public git repositories and terraform registry
          log_level: ${{ inputs.log-level }}
#          check: CKV_AWS_1 # optional: run only a specific check_id. can be comma separated list
