name: Terraform fmt

on:
  workflow_call:
    inputs:
      poweruser_name:
        description: 'Name of github poweruser'
        required: true
        type: string
      poweruser_email:
        description: 'Email of github poweruser'
        required: true
        type: string
      continue_on_error:
        description: 'If true - continue on error'
        required: false
        type: boolean
        default: false
    secrets:
      POWERUSER_GITHUB_ACTIONS_TOKEN:
        required: true
      GIT_CLONE_TOKEN:
        required: true
permissions:
  id-token: write
  contents: write

jobs:
  terraform-fmt:
    runs-on: self-hosted
    continue-on-error: ${{ inputs.continue_on_error }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Configure ability to fetch terraform modules from private repos
        run: |
          git config --global url."https://foo:${{ secrets.GIT_CLONE_TOKEN }}@github.com".insteadOf "ssh://git@github.com"
      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive
        continue-on-error: true
      - name: Commit changes
        run: |
          sudo chown -R $USER:$USER .
          git config --global user.name '${{ inputs.poweruser_name }}'.
          git config --global user.email '${{ inputs.poweruser_email }}'
          git add -- ./\*.tf
          git add -- ./\*.tfvars
          if ! git diff-index --quiet --cached HEAD; then
            git commit -m "[AUTOMATED] Terraform fmt: format the codebase recursively"
          fi
      - name: Push changes for terraform fmt
        uses: ad-m/github-push-action@552c074ed701137ebd2bf098e70c394ca293e87f
        with:
          github_token: ${{ secrets.POWERUSER_GITHUB_ACTIONS_TOKEN }}
          branch: ${{ github.head_ref }}
