name: Terraform plan reusable workflow

on:
  workflow_call:
    inputs:
      lock:
        description: "Terraform lock. If false - don't hold a state lock during the operation"
        required: false
        type: boolean
        default: true
      concurrency-prefix:
        description: "Concurrency prefix"
        required: false
        type: string
        default: "ci"
      project-key:
        description: 'The key of the project used in github oidc AWS role'
        required: true
        type: string
      environment:
        description: Repo environment / terraform workspace name
        required: true
        type: string
      continue-on-error:
        description: 'If true - continue on error'
        required: false
        type: boolean
        default: false
      AWS_REGION:
        description: AWS region
        required: false
        type: string
        default: eu-central-1
    secrets:
      PAT:
        required: true

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  terraform-plan:
    continue-on-error: ${{ inputs.continue-on-error }}
    environment: ${{ inputs.environment }}
    runs-on: self-hosted
    concurrency: ${{ inputs.concurrency-prefix }}-${{ github.ref }}
    steps:
      - name: Configure workflow to fetch private repos
        run: |
          git config --global url."https://foo:${{ secrets.PAT }}@github.com".insteadOf "ssh://git@github.com"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_NUMBER }}:role/github-actions-${{ inputs.project-key }}-${{ inputs.environment }}
          role-session-name: ${{ inputs.project-key }}-${{ inputs.environment }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: "terraform-init::${{ inputs.environment }}"
        id: init
        run: |
          terraform init  -upgrade -backend-config=backend-configs/${{ inputs.environment }}-backend.tfvars && ./resources/tf_ws_select.sh ${{ inputs.environment }}
          terraform validate
      - name: "terraform-plan::${{ inputs.environment }}"
        id: plan
        run: |
          terraform plan -lock=${{ inputs.lock }} -var-file=${{ inputs.environment }}.tfvars
