name: Generate terraform docs

on:
  workflow_call:
    inputs:
      git-push-user-name:
        description: Name to use for commit author
        required: false
        type: string
        default: "github-actions[bot]"
      git-push-user-email:
        description: Email to use for commit author
        required: false
        type: string
        default: "github-actions[bot]@users.noreply.github.com"
      git-commit-message:
        description: Commit message, optional
        required: false
        type: string
        default: "[AUTOMATED] Update README"
      recursive:
        description: If true it will update submodules recursively
        required: false
        type: boolean
        default: false
      recursive-path:
        description: Submodules path to recursively update documentation
        required: false
        type: string
        default: modules
      working-dir:
        description: Comma separated list of directories to generate docs for
        required: false
        type: string
        default: .
    secrets:
      PAT:
        description: PAT of system user (should be able to clone tf repos and pull/push to current repo)
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  docs:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}
      - name: Checkout reusable workflow repo
        uses: actions/checkout@v3
        with:
          ref: master
          repository: EmesaDEV/actions
          path: actions
      - name: GitIgnore terraform-docs config file
        run: |
          mkdir .terraform/
          mv actions/.github/configs/.terraform-docs.yml ./.terraform/
          rm -rf actions
      - name: Generate terraform docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          args: "-c .terraform/.terraform-docs.yml"
          output-file: README.md
          output-method: inject
          git-commit-message: "${{ inputs.git-commit-message }}"
          git-push: true
          git-push-user-email: "${{ inputs.git-push-user-email }}"
          git-push-user-name: "${{ inputs.git-push-user-name }}"
          recursive: ${{ inputs.recursive }}
          recursive-path: ${{ inputs.recursive-path }}
          working-dir: ${{ inputs.working-dir }}
