name: Terraform plan reusable workflow

on:
  workflow_call:
    inputs:
      lock:
        description: "Terraform lock. If false - don't hold a state lock during the operation"
        required: false
        type: boolean
        default: true
      concurrency_prefix:
        description: "Concurrency prefix"
        required: false
        type: string
        default: "ci"
      project_key:
        description: 'The key of the project used in github oidc AWS role'
        required: true
        type: string
      environment:
        description: 'The terraform environment'
        required: true
        type: string
      AWS_REGION:
        description: 'AWS region'
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_NUMBER:
        required: true
      GIT_CLONE_TOKEN:
        required: true

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  terraform-plan:
    environment: ${{ inputs.environment }}
    runs-on: self-hosted
    concurrency: ${{ inputs.concurrency_prefix }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/github-actions-${{ inputs.project_key }}-${{ inputs.environment }}
          role-session-name: ${{ inputs.project_key }}-${{ inputs.environment }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Configure ability to fetch terraform modules from private repos
        run: |
          git config --global url."https://foo:${{ secrets.GIT_CLONE_TOKEN }}@github.com".insteadOf "ssh://git@github.com"
      - name: "terraform-init::${{ inputs.environment }}"
        id: init
        run: |
          terraform init  -upgrade -backend-config=backend-configs/${{ inputs.environment }}-backend.tfvars && ./resources/tf_ws_select.sh ${{ inputs.environment }}
          terraform validate
      - name: "terraform-plan::${{ inputs.environment }}"
        id: plan
        run: |
          terraform plan -lock=${{ inputs.lock }} -var-file=${{ inputs.environment }}.tfvars
