name: Terraform fmt

on:
  workflow_call:
    inputs:
      runs-on:
        description: The type of machine to run the job on. The machine can be either a GitHub-hosted runner, or a self-hosted runner.
        required: false
        type: string
        default: self-hosted
      git-push-user-name:
        description: Name to use for commit author
        required: false
        type: string
        default: "github-actions[bot]"
      git-push-user-email:
        description: Email to use for commit author
        required: false
        type: string
        default: "github-actions[bot]@users.noreply.github.com"
      git-commit-message:
        description: Commit message
        required: false
        type: string
        default: "[AUTOMATED] Format terraform codebase"
      continue-on-error:
        description: If true - continue on error
        required: false
        type: boolean
        default: false
      branch-name:
        description: Name of the branch to commit
        required: false
        type: string
        default: ${{ github.head_ref }} 
    secrets:
      PAT:
        description: PAT of system user (should be able to clone tf repos and pull/push to current repo)
        required: true
permissions:
  id-token: write
  contents: write

jobs:
  terraform-fmt:
    runs-on: ${{ inputs.runs-on }}
    continue-on-error: ${{ inputs.continue-on-error }}
    steps:
      - name: Configure workflow to fetch private repos
        run: |
          git config --global url."https://foo:${{ secrets.PAT }}@github.com".insteadOf "ssh://git@github.com"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch-name }}
          token: ${{ secrets.PAT }}
      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive
        continue-on-error: true
      - name: Commit changes
        run: |
          sudo chown -R $USER:$USER .
          git config --global user.name '${{ inputs.git-push-user-name }}'
          git config --global user.email '${{ inputs.git-push-user-email }}'
          git add -- ./\*.tf
          git add -- ./\*.tfvars
          if ! git diff-index --quiet --cached HEAD; then
            git commit -m "${{ inputs.git-commit-message }}"
          fi
      - name: Push changes for terraform fmt
        uses: ad-m/github-push-action@552c074ed701137ebd2bf098e70c394ca293e87f
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ inputs.branch-name }}
